# Site
name: "uhooaha"
title: "초보 주린이의 투자일지"
description: "주식 시작한지 얼마안된 주린이의 좌충우돌 투자일지"
logo: 'assets/images/profile_icon.png'
favicon: 'assets/images/profile_favicon.png'
# baseurl: /jekyll-theme-memoirs
baseurl: "" #/stock-beginner.github.io  # 리포지토리 이름
url: "https://www.chungchoon98.com"   # 커스텀 도메인
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: uhooaha@kakao.com

# Authors
authors:
  sal:
    name: uhooaha
    display_name: uhooaha
    avatar: 'assets/images/profile_favicon.png'
    email: uhooaha@kakao.com
    # web: https://www.wowthemes.net/donate/
    # twitter: https://twitter.com/wowthemesnet
    description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."
  # john:
    #name: John
    # display_name: John    
    # avatar: 'assets/images/avatar.png'
    # email: wowthemesnet@gmail.com
    # web: https://www.wowthemes.net
    # twitter: https://twitter.com/wowthemesnet
    # description: "Write a short description of the author here. You are currently previewing Memoirs demo, a # Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]


# Rss News
collections:
  stock-news:
    output: true
    permalink: /stock-news/:name/

